export const initialValues = {
  name: '',
  nameRus: '',
  patronymic: '',
  patronymicRus: '',
  surname: '',
  surnameRus: '',
  gender1: '',
  age: '',
  birthday: '',
  serialNumber: '',
  validatedAt: '',
  country: '',
  region: '',
  city: '',
  address: '',
  zipCode: '',
  phone: '',
  email: '',
  emailPassword: ''
};
